--
--    Copyright 2009-2016 the original author or authors.
--
--    Licensed under the Apache License, Version 2.0 (the "License");
--    you may not use this file except in compliance with the License.
--    You may obtain a copy of the License at
--
--       http://www.apache.org/licenses/LICENSE-2.0
--
--    Unless required by applicable law or agreed to in writing, software
--    distributed under the License is distributed on an "AS IS" BASIS,
--    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--    See the License for the specific language governing permissions and
--    limitations under the License.
--

DROP sequence IF EXISTS TestSequence;
DROP TABLE IF EXISTS table1;
DROP TABLE IF EXISTS table2;
DROP TABLE IF EXISTS table3;

CREATE TABLE table1 (
    id   INT GENERATED BY DEFAULT AS identity ( START WITH 11) NOT NULL,
    name VARCHAR(20)
);

CREATE TABLE table2 (
    id        INT GENERATED BY DEFAULT AS identity ( START WITH 22) NOT NULL,
    name      VARCHAR(20),
    name_fred VARCHAR(25) GENERATED ALWAYS AS (name || '_fred')
);

CREATE sequence TestSequence AS INTEGER START WITH 33;

CREATE TABLE table3 (
    id   INT NOT NULL,
    name VARCHAR(20)
);
